# Generated by Django 5.1.6 on 2025-02-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_remove_location_area_sublocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_detalies',
            name='img',
            field=models.FileField(blank=True, db_index=True, null=True, upload_to='category/'),
        ),
    ]
