# Generated by Django 5.1.6 on 2025-02-18 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_business_detalies_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_detalies',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='webapp.sublocation'),
        ),
    ]
