# Generated by Django 5.1.6 on 2025-02-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_enquiryform'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_detalies',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
