# Generated by Django 5.1.6 on 2025-02-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_business_detalies_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_detalies',
            name='close_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='business_detalies',
            name='open_time',
            field=models.IntegerField(default=0),
        ),
    ]
