# Generated by Django 5.1.6 on 2025-02-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_business_detalies_close_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_detalies',
            name='close_time',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='business_detalies',
            name='open_time',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
