# Generated by Django 5.1.6 on 2025-07-21 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_alter_business_detalies_close_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_detalies',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citys', to='webapp.location'),
        ),
    ]
