# Generated by Django 5.1.6 on 2025-07-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_business_detalies_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_detalies',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='business_detalies',
            name='longtitude',
            field=models.FloatField(default=0),
        ),
    ]
