# Generated by Django 5.1.6 on 2025-07-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_alter_business_detalies_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_detalies',
            name='distance',
            field=models.FloatField(default=0),
        ),
    ]
